baseurl = "https://j000sh.com/"
languageCode = "en-US"
title = "j000sh | Josh Lindsay"
theme = "hugo-dusk"
copyright = "© Josh Lindsay - j000sh.com, all rights reserved."

# https://gohugo.io/hosting-and-deployment/hosting-on-github/
publishDir = "public"

googleAnalytics = ""
disqusShortname = ""

enableRobotsTXT = true
canonifyurls = true
paginate = 5

[params.social]
  github = "jlindsay90"
  gitlab = "j000sh"
  twitter = "jlindsay90"
  linkedin = "jlindsay-sf"
  bitbucket = "jlindsay90"
  email = ""

[params.info]
  adsense = "" # Adsense ID (ID only, without ca-pub-)
  enableSocial = false # Adds OpenGraph and Twitter cards
  homeTitle = "" # Title for home page
  poweredby = true # Adds powered by Hugo and Kiss below Copyright section
  related = true # Includes related articles
