baseurl = "/"
languageCode = "en-US"
title = "Josh Lindsay"
theme = "hugo-dusk"

disqusShortname = "shortname"
googleAnalytics = ""
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
Paginate = 5
enableRobotsTXT = true

[permalinks]
  post = "/post/:year/:month/:day/:slug/"
  note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[params]
  description = "Personal website for Josh Lindsay"
  footer = "&copy; [Yihui Xie](https://yihui.name) 2017 | [Github](https://github.com/yihui) | [Twitter](https://twitter.com/xieyihui)"
