baseurl = "/"
languageCode = "en-US"
title = "Josh Lindsay"
theme = "hugo-coder"

preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
paginate = 5
enableRobotsTXT = true

[permalinks]
  post = "/post/:year/:month/:day/:slug/"
  note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
[[menu.main]]
  name = "Posts"
  url = "/posts/"
[[menu.main]]
  name = "Projects"
  url = "/projects/"

[params]
  author = "Josh Lindsay"
  description = "Josh's personal website"
  keywords = "blog,dev,developer,personal,engineer"
  info = "Full Stack Software Engineer"
  gravatar = "jlindsay90@gmail.com"
  colorScheme = "dark"
  custom_css = []
  custom_js = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/josh-dot-com/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab"
    weight = 2
    url = "https://gitlab.com/j000sh/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/jlindsay-sf/"
